### ISSUE TITLE
Exploring Hector with Hector UI 

### ISSUE THREAD

**Issue by kdorheim** [kdorheim/2024.SULI.practice#1]
Objectives 
1.  Use HectorUI to start exploring Hector and understand its dynamics 
2. Practice using Github issues

**Comment by kdorheim** [comment]
First use Hartin et al 2015 answer the following 

* Define in your own words what the model parameters are 
* Make an educated guess as to how increasing or decreasing a parameter value may affect Hector's temperature and CO2 concentrations 

Then 
* Use HectorUI to see the effects of changing the parameter. Did the model behave as you originally expected? Was anything surprising? 

(Share your findings here, to start building some of your GitHub & markdown skills)

**Comment by ptrscll** [comment]
**Definition:** Model parameters are values representing real processes that can't be directly modeled. 

**Changing Different Parameters:**
- Aerosol forcing factor:
  - Prediction: Decreasing the aerosol forcing factor from 1.0 to a smaller value will increase temperatures because aerosols tend to reflect a lot of incoming radiation and have a net cooling effect. With increased temperatures, CO2 will also increase due to processes like decreased CO2 solubility and slower overturning circulation.
  - Results: Decreasing the aerosol forcing factor from 1.0 to 0.3 increased temperatures, particularly during the historical period where the increase in temperature got substantially steeper. CO2 concentrations also increased across the timeframe being studied by about 10 ppmv. I was surprised to see that the aerosol forcing factor had a greater impact on the historical temperatures than future temperatures. Based on the results from changing the volcanic forcing factor, this change might be explained by Hector not modeling large volcanic eruptions in the future.
- CO2 fertilization factor
  - Prediction: Increasing the CO2 fertilization factor will decrease CO2 concentrations (since more vegetation will draw down more CO2) and decrease temperatures (since there'd be less CO2 in the atmosphere).
  - Results: Increasing the CO2 fertilization factor from 0.36 to 0.72 significantly decreased CO2 concentrations and temperatures, with CO2 concentrations being over 60 ppmv lower and temperatures being almost 0.5&deg;C lower by 2100.
- Ocean Heat Diffusivity 
  - Prediction: Increasing ocean heat diffusivity will decrease temperatures since more heat will be able to enter the deep ocean and be removed from the atmosphere. As a result of these cooler temperatures, CO2 will likely decrease due to increased CO2 solubility.
  - Results: Doubling ocean heat diffusivity (from 2.3 to 4.6) led to a decrease in temperature of ~0.1-0.2&deg;C and a decrease in CO2 concentrations by ~5 ppmv. This was a significantly smaller decrease than I expected given how much heat is stored in the oceans.
- Equilibrium Climate Sensitivity
  - Prediction: Increasing equilibrium climate sensitivity should increase temperatures without changing CO2 concentrations, since equilibrium climate sensitivity corresponds to how strongly temperature responds to changes in CO2.
  - Results: Doubling equilibrium climate sensitivity from 3&deg;C to 6&deg;C led to a near-doubling in temperatures and an increase in CO2 concentrations by about 30 ppmv by 2100. The increase in CO2 concentrations was somewhat unexpected, although in retrospect it makes sense given that increased temperatures should also lead to increased CO2 concentrations through decreased solubility, etc.
- Heterotrophic Temperature Sensitivity
  - Prediction: Increasing heterotrophic temperature sensitivity should increase CO2 concentrations (and thus temperatures) because, if heterotrophic respiration is more sensitive to changes in temperature, increases in temperature will produce larger increases in heterotrophic respiration and release more CO2 into the atmosphere.
  - Results: CO2 concentrations increased by nearly 50 ppmv while temperatures increased by a couple tenths of a degree.
- Volcanic forcing scaling factor when heterotrophic temperature sensitivity was doubled to 4.
   - Prediction: Decreasing the volcanic scaling factor should increase temperatures because volcanoes tend to decrease radiative forcing by releasing aerosols that block incoming radiation. This increase in temperatures should lead to an increase in CO2 concentrations, similarly to when the aerosol forcing factor itself was decreased.
   - Results: When the scaling factor was halved to 0.5, temperature drops in the historical period (many of which I assume were associated with large volcanic eruptions) became significantly less severe. However, there were no noticeable changes in temperature predictions for the future or CO2 concentrations at any time. For the CO2 concentrations, I think the lack of change in them may be related to volcanic aerosols only affecting temperatures over a period of a couple years, which may limit how much of an effect they can have on other aspects of the climate system. For the temperatures, I assume the lack of change in temperatures in future projections is the result of Hector not modeling volcanic eruptions occurring in the future because they occur sporadically and have a largely transient effect on the climate system.
